inherit_from: .rubocop_todo.yml

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  DisplayCopNames: true
  TargetRubyVersion: 3.0

Bundler/GemVersion: { EnforcedStyle: forbidden }

Lint/ConstantResolution: { Enabled: false }

Metrics/BlockLength: { Exclude: ["spec/**/*_spec.rb"] }
Style/ClassAndModuleChildren: { EnforcedStyle: compact }

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - describe
    - raise
    - to

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray: { EnforcedStyle: brackets }

Layout/LineLength:
  Max: 80

Style/Copyright: { Enabled: false }
