inherit_from: .rubocop_todo.yml

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  DisplayCopNames: true
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80
