inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  DisplayCopNames: true
  TargetRubyVersion: 3.0

Bundler/GemVersion: { EnforcedStyle: forbidden }

Metrics/BlockLength: { Exclude: ["spec/**/*_spec.rb"] }
Style/ClassAndModuleChildren: { EnforcedStyle: compact }

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - abort
    - describe
    - not_to
    - raise
    - to

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray: { EnforcedStyle: brackets }

Layout/LineLength:
  Max: 80

Bundler/GemComment: { Enabled: false }
Lint/ConstantResolution: { Enabled: false }
Style/ConstantVisibility: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/InlineComment: { Enabled: false }
